# fly.toml app configuration file generated for shiny-gems on 2023-05-03T19:05:01+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "shiny-gems"
primary_region = "mia"

[processes]
  web = "./web.sh"
  worker = "./worker.sh"

[http_service]
  processes = ["web"]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true

[deploy]
  release_command = "bundle exec rake db:migrate"
